# Generated by Django 6.1 on 2026-08-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
