# Generated by Django 6.1 on 2026-08-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Inventory",
            new_name="inventory",
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.author"
            ),
        ),
    ]
